apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab-prod
namePrefix: prod-
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
