apiVersion: v1
kind: Pod
metadata:
  name: liveness-ruim
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      command: ["sh","-c","sleep 60; nginx -g 'daemon off;'"]
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 5
        failureThreshold: 2
