apiVersion: v1
kind: Pod
metadata:
  name: pending-recurso
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      resources:
        requests:
          cpu: "50"
          memory: 200Gi
