apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tommmdl/argocd-lab.git
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-dev
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
